OVERALL FEATURE ENGINEERING STRATEGY ⭐⭐⭐⭐⭐

We will create:

PD features,
LGD features,
EAD features,
Pricing features,
Forecasting features,

step-by-step.

In [1]:
import pandas as pd

pd.set_option('display.max_columns', 500)

df = pd.read_csv(
    "../data/accepted_2007_to_2018q4.csv/accepted_2007_to_2018Q4.csv",
    low_memory=False,
    nrows=50000
)

print(df.shape)

df.head()

(50000, 151)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# STEP 0 — CREATE CLEAN BASE DATAFRAME ⭐⭐⭐⭐⭐

# Run first:

import pandas as pd
import numpy as np

# # ============================================================
# # BASE MODEL DATAFRAME
# # ============================================================

# df_model = df.copy()
# ============================================================
# 1. PD FEATURE ENGINEERING ⭐⭐⭐⭐⭐
# ============================================================
# OBJECTIVE

# Predict:

# probability of default at origination.

# NO leakage.

# STEP 1 — CREATE PD DATAFRAME ⭐⭐⭐⭐⭐
# ============================================================
# PD MODEL DATASET
# ============================================================

pd_df = df.copy()

In [4]:
# STEP 2 — REMOVE LEAKAGE FEATURES ⭐⭐⭐⭐⭐
# ============================================================
# REMOVE LEAKAGE FEATURES
# ============================================================

pd_leakage_cols = [

    "grade",
    "sub_grade",

    "loan_status",

    "last_pymnt_d",
    "next_pymnt_d",
    "last_credit_pull_d",

    "recoveries",
    "collection_recovery_fee",

    "settlement_status",
    "settlement_amount",
    "settlement_percentage",
    "settlement_term",

    "debt_settlement_flag",
    "debt_settlement_flag_date",

    "total_rec_prncp",
    "total_rec_int",

    "out_prncp",
    "out_prncp_inv",

    "hardship_flag",
    "hardship_status",

    "payment_plan_start_date",

    "hardship_amount",
    "hardship_reason",

    "hardship_start_date",
    "hardship_end_date"
]

pd_df = pd_df.drop(

    columns=[

        col for col in pd_leakage_cols

        if col in pd_df.columns
    ],

    errors="ignore"
)

In [6]:
pd_df["issue_d"]

0        Dec-2015
1        Dec-2015
2        Dec-2015
3        Dec-2015
4        Dec-2015
           ...
49995    Nov-2015
49996    Nov-2015
49997    Nov-2015
49998    Nov-2015
49999    Nov-2015
Name: issue_d, Length: 50000, dtype: str

In [12]:
pd_df["earliest_cr_line"]

0       2003-08-01
1       1999-12-01
2       2000-08-01
3       2008-09-01
4       1998-06-01
           ...
49995   2003-09-01
49996   1992-01-01
49997   2011-04-01
49998   1991-08-01
49999   1984-11-01
Name: earliest_cr_line, Length: 50000, dtype: datetime64[us]

In [ ]:

# ============================================================
# SAFE TEMPORAL COLUMNS FOR PD
# ============================================================

temporal_cols = [

    "issue_d",

    "earliest_cr_line"
]
for col in temporal_cols:

    pd_df[col] = pd.to_datetime(

        pd_df[col],

        format="%b-%Y",

        errors="coerce"
    )

In [9]:
for col in temporal_cols:

    pd_df[col] = pd.to_datetime(

        pd_df[col],

        format="%b-%Y",

        errors="coerce"
    )

In [10]:
# STEP 3 — CREDIT HISTORY FEATURES ⭐⭐⭐⭐⭐
# ============================================================
# CREDIT HISTORY FEATURES
# ============================================================

pd_df["credit_history_months"] = (

    (
        pd_df["issue_d"]

        - pd_df["earliest_cr_line"]
    )
    .dt.days
    / 30
)

In [13]:
print(pd_df["earliest_cr_line"][0])
print(pd_df["issue_d"][0])

2003-08-01 00:00:00
2015-12-01 00:00:00

In [14]:
pd_df["credit_history_months"][0]

np.float64(150.16666666666666)

BUSINESS MEANING ⭐⭐⭐⭐⭐

Credit History=Issue Date−Earliest Credit Line

Longer history:

more stable borrower,
richer repayment evidence.

In [15]:
# STEP 4 — UTILIZATION FEATURES ⭐⭐⭐⭐⭐
# ============================================================
# UTILIZATION FEATURES
# ============================================================

pd_df["revol_util_ratio"] = (

    pd_df["revol_util"] / 100
)

pd_df["bc_util_ratio"] = (

    pd_df["bc_util"] / 100
)

pd_df["all_util_ratio"] = (

    pd_df["all_util"] / 100
)

In [16]:
# STEP 5 — DEBT BURDEN FEATURES ⭐⭐⭐⭐⭐
# ============================================================
# DEBT BURDEN FEATURES
# ============================================================

pd_df["installment_income_ratio"] = (

    pd_df["installment"]

    / pd_df["annual_inc"]
)

pd_df["loan_income_ratio"] = (

    pd_df["loan_amnt"]

    / pd_df["annual_inc"]
)

BUSINESS LOGIC ⭐⭐⭐⭐⭐

Higher burden:

Debt Burden=
Income
Debt
	​


Usually:

higher stress,
higher default probability.

In [18]:
pd_df["credit_history_months"]

0        150.166667
1        194.800000
2        186.666667
3         88.233333
4        213.066667
            ...
49995    148.133333
49996    290.166667
49997     55.833333
49998    295.266667
49999    377.400000
Name: credit_history_months, Length: 50000, dtype: float64

In [20]:
# STEP 6 — CREDIT ACTIVITY FEATURES ⭐⭐⭐⭐⭐
# ============================================================
# CREDIT ACTIVITY FEATURES
# ============================================================

pd_df["accounts_per_year"] = (

    pd_df["total_acc"]

    / (
        (pd_df["credit_history_months"] / 12)

        + 1
    )
)
# INTERPRETATION ⭐⭐⭐⭐⭐

# Aggressive account growth:

# credit expansion,
# potential leverage stress.

WHAT THIS FEATURE REPRESENTS ⭐⭐⭐⭐⭐
accounts_per_year
=
total_acc
/
credit_history_years

Conceptually:

Accounts Per Year=
Years of Credit History
Total Accounts
	​


BUSINESS INTERPRETATION ⭐⭐⭐⭐⭐

This estimates:

how aggressively borrower accumulates credit.
EXAMPLE ⭐⭐⭐⭐⭐
Customer A
Metric	Value
total_acc	30
credit history	15 years

Then:
30/
15

	​

=2

Meaning:
~2 accounts opened per year.

Likely:

stable growth.
Customer B
Metric	Value
total_acc	30
credit history	3 years

Then:
30/
3

	​

=10

Meaning:
~10 accounts per year.

This may indicate:

aggressive borrowing,
rapid leverage expansion,
elevated risk appetite.

VERY important behavioral signal.

In [21]:
# STEP 7 — TEMPORAL MACRO FEATURES ⭐⭐⭐⭐⭐
# ============================================================
# TEMPORAL MACRO FEATURES
# ============================================================

pd_df["issue_year"] = (

    pd_df["issue_d"].dt.year
)

pd_df["issue_month"] = (

    pd_df["issue_d"].dt.month
)

pd_df["issue_quarter"] = (

    pd_df["issue_d"].dt.quarter
)
# WHY IMPORTANT ⭐⭐⭐⭐⭐

# Captures:

# economic cycles,
# seasonal issuance behavior,
# recession periods.

In [22]:
# STEP 8 — MISSINGNESS FEATURES ⭐⭐⭐⭐⭐

# VERY important.

# ============================================================
# MISSINGNESS INDICATORS
# ============================================================

important_missing = [

    "all_util",
    "il_util",
    "mths_since_last_delinq"
]

for col in important_missing:

    pd_df[f"{col}_missing"] = (

        pd_df[col]
        .isnull()
        .astype(int)
    )

In [23]:
# STEP 9 — SAFE IMPUTATION ⭐⭐⭐⭐⭐
# ============================================================
# SAFE IMPUTATION
# ============================================================

pd_df = pd_df.fillna({

    "all_util": -999,

    "il_util": -999,

    "bc_util": -999,

    "mths_since_last_delinq": 999,

    "mths_since_last_record": 999
})

In [25]:
pd_df.head(2)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_pymnt,total_pymnt_inv,total_rec_late_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_type,deferral_term,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,settlement_date,credit_history_months,revol_util_ratio,bc_util_ratio,all_util_ratio,installment_income_ratio,loan_income_ratio,accounts_per_year,issue_year,issue_month,issue_quarter,all_util_missing,il_util_missing,mths_since_last_delinq_missing
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,leadman,10+ years,MORTGAGE,55000.0,Not Verified,2015-12-01,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,2003-08-01,675.0,679.0,1.0,30.0,999.0,7.0,0.0,2765.0,29.7,13.0,w,4421.723917,4421.72,0.0,122.67,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,150.166667,0.297,0.372,0.34,0.002237,0.065455,0.961973,2015,12,4,0,0,0
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,2015-12-01,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,1999-12-01,715.0,719.0,4.0,6.0,999.0,22.0,0.0,21470.0,19.2,38.0,w,25679.660000,25679.66,0.0,926.35,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,194.800000,0.192,0.271,0.29,0.012620,0.380000,2.205029,2015,12,4,0,0,0

In [26]:
# IMPORTANT CATCHES ⭐⭐⭐⭐⭐
# 1. term IS STILL STRING ⭐⭐⭐⭐⭐

# Currently:

# "36 months"

# This is bad for ML.

# FIX ⭐⭐⭐⭐⭐

# Convert:

pd_df["term_months"] = (

    pd_df["term"]

    .str.extract(r"(\d+)")

    .astype(float)
)

# Then later:
# drop original:

pd_df.drop(columns=["term"], inplace=True)

In [27]:
# 2. emp_length STILL CATEGORICAL ⭐⭐⭐⭐⭐

# Currently:

# "10+ years"

# This should become numeric.

# FIX ⭐⭐⭐⭐⭐
pd_df["emp_length_years"] = (

    pd_df["emp_length"]

    .str.extract(r"(\d+)")

    .astype(float)
)

# Fill missing:

pd_df["emp_length_years"] = (

    pd_df["emp_length_years"]

    .fillna(0)
)

In [28]:
# 3. URL COLUMN IS USELESS ⭐⭐⭐⭐⭐

# You still have:

# url

# This should be removed immediately.

# FIX ⭐⭐⭐⭐⭐
pd_df.drop(columns=["url"], inplace=True)

In [ ]:
4. TITLE / EMP_TITLE MAY CAUSE MASSIVE CARDINALITY ⭐⭐⭐⭐⭐
# high cardinality.

# You currently have:
# thousands of unique job titles:

# "Engineer"
# "Senior Engineer"
# "Software Engineer"
# "truck driver"
# "Driver"
# "Owner/operator"
# etc.

In [36]:
# MY RECOMMENDATION FOR REPO 5 ⭐⭐⭐⭐⭐

# Start simple but smart:

# STEP 1 — CLEAN TITLES
# STEP 2 — GROUP RARE JOBS
# STEP 3 — TARGET/FREQUENCY ENCODE

# This is already VERY strong.

# Later:
# upgrade to:

# sentence embeddings,
# transformer embeddings,
# occupation clustering.
# STEP 1 — CLEAN EMP_TITLE ⭐⭐⭐⭐⭐

# Run:

# ============================================================
# CLEAN EMP TITLE
# ============================================================

pd_df["emp_title_clean"] = (

    pd_df["emp_title"]

    .str.lower()

    .str.strip()
)
# STEP 2 — REMOVE SPECIAL CHARACTERS ⭐⭐⭐⭐⭐
pd_df["emp_title_clean"] = (

    pd_df["emp_title_clean"]

    .str.replace(

        r"[^a-zA-Z\s]",

        "",

        regex=True
    )
)
# STEP 3 — HANDLE MISSING ⭐⭐⭐⭐⭐
pd_df["emp_title_clean"] = (

    pd_df["emp_title_clean"]

    .fillna("unknown")
)
# STEP 4 — CHECK TOP JOBS ⭐⭐⭐⭐⭐
pd_df["emp_title_clean"].value_counts().head(30)

emp_title_clean
unknown                     2995
teacher                     1227
manager                     1108
owner                        883
registered nurse             557
supervisor                   541
driver                       528
sales                        469
rn                           440
project manager              342
general manager              331
truck driver                 295
office manager               289
director                     288
president                    259
engineer                     233
sales manager                231
vice president               207
operations manager           192
technician                   181
police officer               175
nurse                        171
mechanic                     170
accountant                   167
attorney                     166
store manager                164
account manager              153
administrative assistant     150
assistant manager            149
analyst                      130
Name: count, dtype: int64

In [39]:
## all_util — 57% missing ⭐⭐⭐⭐⭐ Combined utilization metric. IMPORTANT QUESTION ⭐⭐⭐⭐⭐ We must later investigate: Is missingness random? OR correlated with:

# HYPOTHESIS TESTS ⭐⭐⭐⭐⭐

# We want to test:

# Hypothesis	Meaning
# missing random	no business meaning
# missing = thin file	customer lacks enough credit history
# missing = low utilization	no active debt
# missing = risky customers	hidden deterioration
# missing = safe customers	financially inactive


# ============================================================
# CLEAN TARGET CREATION
# ============================================================

bad_status = [

    "Charged Off",

    "Default"
]

good_status = [

    "Fully Paid"
]

df_pd = df[

    df["loan_status"].isin(
        bad_status + good_status
    )

].copy()

df_pd["TARGET"] = (

    df_pd["loan_status"]
    .isin(bad_status)

).astype(int)

# ============================================================
# TARGET DISTRIBUTION
# ============================================================

print(

    df_pd["TARGET"]
    .value_counts(normalize=True)

)

TARGET
0    0.794846
1    0.205154
Name: proportion, dtype: float64

In [40]:
# ============================================================
# REATTACH TARGET
# ============================================================

pd_df["TARGET"] = df_pd["TARGET"]

In [41]:
# ENTERPRISE-STYLE JOB CLUSTERING ⭐⭐⭐⭐⭐

# Create:

# Cluster	Example Titles
# healthcare	rn, nurse, registered nurse
# management	manager, director, vp
# engineering	engineer, technician
# transportation	driver, truck driver
# finance	accountant, analyst
# legal	attorney
# admin	office manager, assistant
# sales	sales, sales manager
# government	police officer
# self_employed	owner, president

# This becomes:

# interpretable occupational risk segmentation.

# VERY enterprise-friendly.

# STEP 1 — CREATE JOB CLUSTERS ⭐⭐⭐⭐⭐

# Run:

# ============================================================
# JOB CLUSTERING
# ============================================================

job_cluster_map = {

    # HEALTHCARE
    "registered nurse": "healthcare",
    "rn": "healthcare",
    "nurse": "healthcare",

    # MANAGEMENT
    "manager": "management",
    "general manager": "management",
    "assistant manager": "management",
    "operations manager": "management",
    "project manager": "management",
    "director": "management",
    "vice president": "management",

    # ENGINEERING / TECH
    "engineer": "engineering",
    "technician": "engineering",

    # TRANSPORT
    "driver": "transportation",
    "truck driver": "transportation",

    # SALES
    "sales": "sales",
    "sales manager": "sales",
    "account manager": "sales",

    # FINANCE
    "accountant": "finance",
    "analyst": "finance",

    # LEGAL
    "attorney": "legal",

    # ADMIN
    "office manager": "admin",
    "administrative assistant": "admin",

    # GOVERNMENT
    "police officer": "government",

    # SELF EMPLOYED / EXECUTIVE
    "owner": "self_employed",
    "president": "executive"
}
# STEP 2 — MAP JOBS ⭐⭐⭐⭐⭐
pd_df["job_cluster"] = (

    pd_df["emp_title_clean"]

    .map(job_cluster_map)
)
# STEP 3 — HANDLE UNMAPPED JOBS ⭐⭐⭐⭐⭐
pd_df["job_cluster"] = (

    pd_df["job_cluster"]

    .fillna("other")
)
# STEP 4 — INVESTIGATE DEFAULT RISK ⭐⭐⭐⭐⭐

# VERY important EDA.

# Run:

(
    pd_df
    .groupby("job_cluster")["TARGET"]
    .mean()
    .sort_values()
    * 100
)

job_cluster
legal             14.084507
engineering       18.662953
finance           18.750000
healthcare        19.605911
other             20.316823
management        20.566767
sales             20.685112
government        22.297297
executive         23.076923
self_employed     23.447402
admin             23.466667
transportation    28.246319
Name: TARGET, dtype: float64

In [43]:
pd_df["job_cluster"].value_counts()

job_cluster
other             41906
management         2617
healthcare         1168
self_employed       883
sales               853
transportation      823
admin               439
engineering         414
finance             297
executive           259
government          175
legal               166
Name: count, dtype: int64

In [44]:
# 5. ZIP CODE IS PARTIAL ⭐⭐⭐⭐⭐

# You have:

# 190xx

# This is interesting because:
# it contains:

# regional risk signal.

# BUT:
# high cardinality.

# RECOMMENDATION ⭐⭐⭐⭐⭐

# Extract first 3 digits:

pd_df["zip_region"] = (

    pd_df["zip_code"]

    .str.extract(r"(\d+)")
)

In [45]:
# 6. issue_year HAS NO VARIANCE ⭐⭐⭐⭐⭐

# Your sample seems entirely:

# 2015

# This means:
# feature useless in current subset.

# CHECK ⭐⭐⭐⭐⭐

# Run:

pd_df["issue_year"].value_counts()

issue_year
2015    50000
Name: count, dtype: int64

In [46]:
# 7. policy_code LIKELY CONSTANT ⭐⭐⭐⭐⭐

# Check:

pd_df["policy_code"].value_counts()

# Usually:
# always:

# 1

# If so:
# drop it.

policy_code
1.0    50000
Name: count, dtype: int64

In [47]:
# 9. MANY SECONDARY APPLICANT FEATURES ARE 100% MISSING ⭐⭐⭐⭐⭐

# Examples:

# sec_app_*
# revol_bal_joint

# These should likely be dropped for now.

# Because:
# missingness is:

# structural.
# RECOMMENDATION ⭐⭐⭐⭐⭐

# Drop:

sec_cols = [

    col for col in pd_df.columns

    if "sec_app" in col
]

# and:

pd_df.drop(columns=sec_cols, inplace=True)

In [48]:
# 10. pymnt_plan MAY BE LEAKAGE-LIKE ⭐⭐⭐⭐⭐

# This can represent:

# already distressed repayment restructuring.

# Need business caution.

# I recommend:
# DROP for origination PD.

# ============================================================
# DROP pymnt_plan
# ============================================================

pd_df.drop(

    columns=["pymnt_plan"],

    inplace=True,

    errors="ignore"
)

In [49]:
pd_df["TARGET"].value_counts()

TARGET
0.0    34978
1.0     9028
Name: count, dtype: int64

In [50]:
# 12. HUGE IMPORTANT CATCH ⭐⭐⭐⭐⭐

# You STILL HAVE:

# total_pymnt
# total_pymnt_inv
# last_pymnt_amnt

# These are:

# MASSIVE leakage.

# Because:
# they already contain repayment outcome.

# REMOVE IMMEDIATELY ⭐⭐⭐⭐⭐
payment_leakage = [

    "total_pymnt",

    "total_pymnt_inv",

    "last_pymnt_amnt"
]

pd_df.drop(

    columns=payment_leakage,

    inplace=True,

    errors="ignore"
)

In [51]:
# 13. POTENTIAL HIDDEN LEAKAGE ⭐⭐⭐⭐⭐

# You still have:

# last_fico_range_high
# last_fico_range_low

# This is:

# future bureau pull.

# Leakage.

# DROP.

# REMOVE ⭐⭐⭐⭐⭐
pd_df.drop(

    columns=[

        "last_fico_range_high",

        "last_fico_range_low"
    ],

    inplace=True,

    errors="ignore"
)

In [53]:
pd_df.drop(

    columns=["id"],

    inplace=True,

    errors="ignore"
)

In [54]:
pd_df.drop(

    columns=["member_id"],

    inplace=True,

    errors="ignore"
)

In [55]:
pd_df.drop(

    columns=["desc"],

    inplace=True,

    errors="ignore"
)

In [56]:
pd_df.drop(

    columns=["title"],

    inplace=True,

    errors="ignore"
)

In [57]:
# initial_list_status IS TRICKY ⭐⭐⭐⭐⭐

# Values:

# w
# f

# This may reflect:

# platform funding mechanics,
# investor demand,
# loan processing.

# Potentially mildly leakage-like.

# I recommend:
# drop initially.

# DROP ⭐⭐⭐⭐⭐
pd_df.drop(

    columns=["initial_list_status"],

    inplace=True,

    errors="ignore"
)
# policy_code IS USELESS ⭐⭐⭐⭐⭐

# Almost certainly constant.

# Check:

pd_df["policy_code"].value_counts()

# If one value only:
# drop.

policy_code
1.0    50000
Name: count, dtype: int64

In [58]:
pd_df.drop(

    columns=["policy_code"],

    inplace=True,

    errors="ignore"
)

In [59]:
pd_df.head(10
)

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,purpose,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_rec_late_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,hardship_type,deferral_term,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,settlement_date,credit_history_months,revol_util_ratio,bc_util_ratio,all_util_ratio,installment_income_ratio,loan_income_ratio,accounts_per_year,issue_year,issue_month,issue_quarter,all_util_missing,il_util_missing,mths_since_last_delinq_missing,term_months,emp_length_years,zip_region,emp_title_clean,job_cluster,TARGET
0,3600.0,3600.0,3600.0,13.99,123.03,leadman,10+ years,MORTGAGE,55000.0,Not Verified,2015-12-01,debt_consolidation,190xx,PA,5.91,0.0,2003-08-01,675.0,679.0,1.0,30.0,999.0,7.0,0.0,2765.0,29.7,13.0,0.0,0.0,30.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,150.166667,0.297,0.372,0.34,0.002237,0.065455,0.961973,2015,12,4,0,0,0,36.0,10.0,190,leadman,other,0.0
1,24700.0,24700.0,24700.0,11.99,820.28,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,2015-12-01,small_business,577xx,SD,16.06,1.0,1999-12-01,715.0,719.0,4.0,6.0,999.0,22.0,0.0,21470.0,19.2,38.0,0.0,0.0,NaN,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,194.800000,0.192,0.271,0.29,0.012620,0.380000,2.205029,2015,12,4,0,0,0,36.0,10.0,577,engineer,engineering,0.0
2,20000.0,20000.0,20000.0,10.78,432.66,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,2015-12-01,home_improvement,605xx,IL,10.78,0.0,2000-08-01,695.0,699.0,0.0,999.0,999.0,6.0,0.0,7869.0,56.2,18.0,0.0,0.0,NaN,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,186.666667,0.562,0.559,0.65,0.006868,0.317460,1.087248,2015,12,4,0,0,1,60.0,10.0,605,truck driver,transportation,0.0
3,35000.0,35000.0,35000.0,14.85,829.90,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,2015-12-01,debt_consolidation,076xx,NJ,17.06,0.0,2008-09-01,785.0,789.0,0.0,999.0,999.0,13.0,0.0,7802.0,11.6,17.0,0.0,0.0,NaN,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,88.233333,0.116,0.121,0.45,0.007545,0.318182,2.035251,2015,12,4,0,0,1,60.0,10.0,076,information systems officer,other,NaN
4,10400.0,10400.0,10400.0,22.45,289.91,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,2015-12-01,major_purchase,174xx,PA,25.37,1.0,1998-06-01,695.0,699.0,3.0,12.0,999.0,12.0,0.0,21929.0,64.5,35.0,0.0,0.0,NaN,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,213.066667,0.645,0.775,0.78,0.002776,0.099585,1.866114,2015,12,4,0,0,0,60.0,3.0,174,contract specialist,other,0.0
5,11950.0,11950.0,11950.0,13.44,405.18,Veterinary Tecnician,4 years,RENT,34000.0,Source Verified,2015-12-01,debt_consolidation,300xx,GA,10.20,0.0,1987-10-01,690.0,694.0,0.0,999.0,999.0,5.0,0.0,8822.0,68.4,6.0,0.0,0.0,NaN,Individual,NaN,NaN,NaN,0.0,0.0,12798.0,0.0,1.0,0.0,0.0,338.0,3976.0,99.0,0.0,0.0,4522.0,76.0,12900.0,0.0,0.0,0.0,0.0,2560.0,844.0,91.0,0.0,0.0,338.0,54.0,32.0,32.0,0.0,36.0,NaN,NaN,NaN,0.0,2.0,3.0,2.0,2.0,2.0,4.0,4.0,3.0,5.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,342.933333,0.684,0.910,0.76,0.011917,0.351471,0.202855,2015,12,4,0,0,1,36.0,4.0,300,veterinary tecnician,other,0.0
6,20000.0,20000.0,20000.0,9.17,637.58,Vice President of Recruiting Operations,10+ years,MORTGAGE,180000.0,Not Verified,2015-12-01,debt_consolidation,550xx,MN,14.67,0.0,1990-06-01,680.0,684.0,0.0,49.0,999.0,12.0,0.0,87329.0,84.5,27.0,0.0,0.0,NaN,Individual,NaN,NaN,NaN,0.0,0.0,360358.0,0.0,2.0,0.0,2.0,18.0,29433.0,63.0,2.0,3.0,13048.0,74.0,94200.0,1.0,0.0,1.0,6.0,30030.0,0.0,102.9,0.0,0.0,142.0,306.0,10.0,10.0,4.0,12.0,NaN,10.0,NaN,0.0,4.0,6.0,4.0,5.0,7.0,9.0,16.0,6.0,12.0,0.0,0.0,0.0,2.0,96.3,100.0,0.0,0.0,388852.0,116762.0,31500.0,46452.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,310.466667,0.845,1.029,0.74,0.003542,0.111111,1.004755,2015,12,4,0,0,0,36.0,10.0,550,vice president of recruiting operations,other,0.0
7,20000.0,20000.0,20000.0,8.49,631.26,road driver,10+ years,MORTGAGE,85000.0,Not Verified,2015-12-01,major_purchase,293xx,SC,17.61,1.0,1999-02-01,705.0,709.0,0.0,3.0,999.0,8.0,0.0,826.0,5.7,15.0,0.0,0.0,3.0,Individual,NaN,NaN,NaN,0.0,0.0,141601.0,0.0,3.0,0.0,4.0,13.0,27111.0,75.0,0.0,0.0,640.0,55.0,14500.0,1.0,0.0,2.0,4.0,17700.0,13674.0,5.7,0.0,0.0,149.0,55.0,32.0,13.0,3.0,32.0,NaN,8.0,NaN,1.0,2.0,2.0,3.0,3.0,9.0,3.0,3.0,2.0,8.0,0.0,0.0,1.0,0.0,93.3,0.0,0.0,0.0,193390.0,27937.0,14500.0,36144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,204.900000,0.057,0.057,0.55,0.007427,0.235294,0.829876,2015,12,4,0,0,0,36.0,10.0,293,road driver,other,0.0
8,10000.0,10000.0,10000.0,6.49,306.45,SERVICE MANAGER,6 years,RENT,85000.0,Not Verified,2015-12-01,credit_card,160xx,PA,13.07,0.0,2002-04-01,685.0,689.0,1.0,999.0,106.0,14.0,1.0,10464.0,34.5,23.0,0.0,0.0,NaN,Individual,NaN,NaN,NaN,0.0,8341.0,27957.0,2.0,1.0,0.0,0.0,35.0,17493.0,57.0,2.0,7.0,2524.0,46.0,30300.0,2.0,0.0,1.0,7.0,1997.0,8182.0,50.1,0.0,0.0,164.0,129.0,1.0,1.0,1.0,4.0,NaN,1.0,NaN,0.0,6.0,9.0,7.0,10.0,3.0,13.0,19.0,9.0,14.0,0.0,0.0,0.0,2.0,95.7,28.6,1.0,0.0,61099.0,27957.0,16400.0,30799.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,166.400000,0.345,0.501,0.46,0.003605,0.117647,1.547085,2015,12,4,0,0,1,36.0,6.0,160,service manager,other,0.0
9,8000.0,8000.0,8000.0,11.48,263.74,Vendor liaison,10+ years,MORTGAGE,42000.0,Not Verified,2015-12-01,credit_card,029xx,RI,34.80,0.0,1994-11-01,700.0,704.0,0.0,75.0,999.0,8.0,0.0,7034.0,39.1,18.0,0.0,0.0,75.0,Individual,NaN,NaN,NaN,0.0,0.0,199696.0,0.0,2.0,2.0,3.0,10.0,106748.0,72.0,0.0,2.0,4725.0,49.0,18000.0,0.0,0.0,1.0,5.0,28528.0,9966.0,41.4,0.0,0.0,155.0,253.0,15.0,10.0,1.0,50.0,NaN,10.0,NaN,1.0,3.0,3.0,3.0,6.0,5.0,5.0,11.0,3.0,8.0,0.0,0.0,0.0,2.0,94.4,33.3,0.0,0.0,256513.0,113782.0,17000.0,135513.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,NaN,256.666667,0.391,0.414,0.49,0.006280,0.190476,0.803970,2015,12,4,0,0,0,36.0,10.0,029,vendor liaison,other,0.0

In [63]:
pd_df["TARGET"]

0        0.0
1        0.0
2        0.0
3        NaN
4        0.0
        ...
49995    1.0
49996    0.0
49997    0.0
49998    0.0
49999    0.0
Name: TARGET, Length: 50000, dtype: float64

In [62]:
# SAVE DATASET ⭐⭐⭐⭐⭐

# You can save your engineered PD dataset using:

# ============================================================
# SAVE PD DATASET
# ============================================================

pd_df.to_parquet(

    "/home/muzzi/enterprise_credit_risk_forecasting/data/pd_dataset.parquet",

    index=False
)

# OR CSV:

pd_df.to_csv(

    "/home/muzzi/enterprise_credit_risk_forecasting/data/pd_dataset.csv",

    index=False
)

In [ ]:
NOW THE IMPORTANT CONCEPTUAL QUESTION ⭐⭐⭐⭐⭐
WHAT TYPE OF PD MODEL ARE YOU BUILDING?

Based on your current features:

Feature Type	Timing
fico	application time
annual income	application time
employment	application time
purpose	application time
utilization	bureau pull at application
loan amount	application time
occupation	application time

You are currently building:

ORIGINATION PD MODEL ⭐⭐⭐⭐⭐

Meaning:

PD=P(Default after loan origination)

using:

information available when customer applies.
THIS IS USED FOR ⭐⭐⭐⭐⭐
Banking Decision	Purpose
approve / reject	underwriting
pricing	interest rate
risk-based segmentation	portfolio control
capital estimation	Basel
initial credit strategy	acquisition
WHAT YOU ARE NOT YET BUILDING ⭐⭐⭐⭐⭐

You are NOT yet building:

BEHAVIORAL / MONITORING PD

which predicts:

PD=P(Future Default ∣ Existing Customer Behavior)

This is:

dynamic ongoing risk monitoring.

VERY different.

DIFFERENCE BETWEEN BOTH ⭐⭐⭐⭐⭐
Aspect	Origination PD	Behavioral PD
timing	before approval	after loan active
objective	should we lend?	will risk deteriorate?
data	application + bureau	repayment behavior
temporal?	mostly static	dynamic
monitoring?	no	yes
updates?	once	monthly/weekly
use case	underwriting	collections / EWS
YOUR CURRENT FEATURES ARE ⭐⭐⭐⭐⭐

Mostly:

static origination features.

Examples:

Feature	Origination?
fico	yes
annual_inc	yes
job_cluster	yes
dti	yes
revol_util	yes
loan_amnt	yes

These are:

known BEFORE loan issuance.
FEATURES REQUIRED FOR TRUE MONITORING PD ⭐⭐⭐⭐⭐

You would need:

Behavioral Feature	Meaning
payment history over time	repayment consistency
missed payments trend	deterioration
utilization trend	worsening leverage
balance growth	increasing stress
delinquency trajectory	progressive distress
transaction behavior	spending stress
monthly snapshots	temporal evolution

Example:

customer	month	utilization	missed_payments
A	Jan	30%	0
A	Feb	45%	0
A	Mar	72%	1

THIS becomes:

behavioral risk forecasting.
VERY IMPORTANT ⭐⭐⭐⭐⭐

Your current LendingClub dataset:
mostly contains:

snapshot-style origination data.

NOT full behavioral monthly history.

That is why:
your current repo naturally fits:

Origination PD
Expected Loss
Pricing
Portfolio segmentation

VERY well.

SO WHAT SHOULD YOU CALL THIS MODEL? ⭐⭐⭐⭐⭐

Correct enterprise naming:

Application / Origination PD Model

OR:

Underwriting PD Model
WHAT WOULD A MONITORING MODEL BE CALLED? ⭐⭐⭐⭐⭐
Name	Meaning
Behavioral PD	dynamic borrower behavior
Account Management PD	ongoing risk
Early Warning System	deterioration prediction
Watchlist Model	pre-default monitoring
Collection Risk Model	recovery prioritization
IMPORTANT ENTERPRISE STRATEGY ⭐⭐⭐⭐⭐

Repo 5 can evolve into:

Layer	Purpose
Origination PD	should we lend?
LGD	how much lose?
EAD	exposure size
Pricing	profitability
Behavioral PD	ongoing deterioration
Early Warning	intervention
Collections Optimization	recovery strategy

This becomes:

full enterprise credit lifecycle AI.

In [ ]:
14. ENCODING STILL REQUIRED ⭐⭐⭐⭐⭐

You still have categorical variables:

Feature
purpose
home_ownership
verification_status
addr_state
application_type

Need:

one-hot encoding,
OR:
CatBoost.

In [ ]:
============================================================
2. LGD FEATURE ENGINEERING ⭐⭐⭐⭐⭐
============================================================

ONLY DEFAULTED LOANS.

STEP 1 — FILTER DEFAULTS ⭐⭐⭐⭐⭐
# ============================================================
# LGD DATASET
# ============================================================

lgd_df = df_model[

    df_model["TARGET"] == 1

].copy()
STEP 2 — ENGINEER REMAINING EXPOSURE ⭐⭐⭐⭐⭐
# ============================================================
# REMAINING EXPOSURE
# ============================================================

lgd_df["remaining_exposure"] = (

    lgd_df["funded_amnt"]

    - lgd_df["total_rec_prncp"]
)

lgd_df["remaining_exposure"] = (

    lgd_df["remaining_exposure"]

    .clip(lower=1)
)
STEP 3 — ENGINEER LGD TARGET ⭐⭐⭐⭐⭐
# ============================================================
# LGD TARGET
# ============================================================

lgd_df["recovery_rate"] = (

    lgd_df["recoveries"]

    / lgd_df["remaining_exposure"]
)

lgd_df["recovery_rate"] = (

    lgd_df["recovery_rate"]

    .clip(0,1)
)

lgd_df["LGD_TARGET"] = (

    1

    - lgd_df["recovery_rate"]
)
STEP 4 — REMOVE LEAKAGE ⭐⭐⭐⭐⭐
# ============================================================
# REMOVE LEAKAGE
# ============================================================

lgd_leakage = [

    "recoveries",

    "collection_recovery_fee",

    "settlement_amount",

    "settlement_percentage",

    "settlement_term",

    "settlement_status",

    "total_rec_prncp",

    "out_prncp",

    "out_prncp_inv"
]

lgd_df = lgd_df.drop(

    columns=[

        col for col in lgd_leakage

        if col in lgd_df.columns
    ],

    errors="ignore"
)
STEP 5 — LGD FEATURES ⭐⭐⭐⭐⭐

Use:

borrower stability,
exposure structure,
financial stress.
lgd_features = [

    "loan_amnt",

    "term",

    "int_rate",

    "annual_inc",

    "dti",

    "revol_util",

    "credit_history_months",

    "mort_acc",

    "home_ownership"
]
============================================================
3. EAD FEATURE ENGINEERING ⭐⭐⭐⭐⭐
============================================================
# ============================================================
# EAD DATASET
# ============================================================

ead_df = df_model.copy()
TARGET ⭐⭐⭐⭐⭐
ead_df["EAD_TARGET"] = (

    ead_df["funded_amnt"]

    - ead_df["total_rec_prncp"]
)

ead_df["EAD_TARGET"] = (

    ead_df["EAD_TARGET"]

    .clip(lower=0)
)
EAD FEATURES ⭐⭐⭐⭐⭐
ead_features = [

    "loan_amnt",

    "installment",

    "term",

    "int_rate",

    "revol_util",

    "dti",

    "annual_inc",

    "credit_history_months"
]
============================================================
4. PRICING MODEL FEATURES ⭐⭐⭐⭐⭐
============================================================

Pricing uses:

outputs of risk models.
PRICING DATASET ⭐⭐⭐⭐⭐
pricing_df = pd.DataFrame()

pricing_df["predicted_PD"] = pd_predictions

pricing_df["predicted_LGD"] = lgd_predictions

pricing_df["predicted_EAD"] = ead_predictions
PROFIT TARGET ⭐⭐⭐⭐⭐
pricing_df["expected_loss"] = (

    pricing_df["predicted_PD"]

    * pricing_df["predicted_LGD"]

    * pricing_df["predicted_EAD"]
)
RISK-BASED PRICING ⭐⭐⭐⭐⭐

Conceptually:

Required Interest∝Expected Loss+Margin

============================================================
5. FORECASTING FEATURE ENGINEERING ⭐⭐⭐⭐⭐
============================================================

MOST IMPORTANT FUTURE AREA.

FORECAST DATASET ⭐⭐⭐⭐⭐
forecast_df = pd_df.copy()
FORECAST FEATURES ⭐⭐⭐⭐⭐

Focus:

temporal behavior,
stress trajectory,
macro timing.
TEMPORAL FEATURES ⭐⭐⭐⭐⭐
forecast_df["loan_age_proxy"] = (

    2020

    - forecast_df["issue_year"]
)
STRESS FEATURES ⭐⭐⭐⭐⭐
forecast_df["stress_score"] = (

    forecast_df["dti"]

    * forecast_df["revol_util_ratio"]
)
CREDIT HUNGER ⭐⭐⭐⭐⭐
forecast_df["credit_hunger"] = (

    forecast_df["inq_last_6mths"]

    / (
        forecast_df["total_acc"] + 1
    )
)
BEHAVIORAL RISK ⭐⭐⭐⭐⭐
forecast_df["delinq_intensity"] = (

    forecast_df["delinq_2yrs"]

    / (
        forecast_df["credit_history_months"] + 1
    )
)
FINAL IMPORTANT RECOMMENDATION ⭐⭐⭐⭐⭐

Before ANY training:
always create:

train / validation / out-of-time split

VERY important for:

temporal realism,
avoiding future leakage,
enterprise governance.

Especially:
use:

issue_year

for:

out-of-time validation.